Suggestion for adding model option
peterdemin/openai-cli pull request #1
Opened 2022-12-21 07:20 UTC by azhx

Just a suggestion to add an option for specifying the model as an environment variable, rather than hardcoding text-davinci-003.

2022-12-21 07:49 UTC, azhx commented
maybe in the future add something to error if the model spec doesn't exist, idk, i spent like 30 min on this

2022-12-23 03:46 UTC, peterdemin requested changes

2022-12-23 03:46 UTC, peterdemin commented on src/openai_cli/cli.py
> +@click.option('-m', "--model", default="", help="OpenAI model option")
text-davinci-003 is the most advanced model, I think it's to have it as a default here.

2022-12-23 03:46 UTC, peterdemin commented on src/openai_cli/cli.py
> +        model = os.environ.get("OPENAI_MODEL", "")
Let's drop the environment option here. I find it confusing to have this configured through env.

2022-12-23 03:46 UTC, peterdemin commented on src/openai_cli/cli.py
> +        print("OPENAI_MODEL environment variable not set. Defaulting to text-davinci-003")
Without the env var support, this print statement can be dropped too.

2022-12-23 03:46 UTC, peterdemin commented on src/openai_cli/client.py
>      def generate_response(self, prompt: str, model: str = "text-davinci-003") -> str:
Let's drop the model parameter here too, we don't need to have two ways to pass it.

2022-12-29 18:11 UTC, peterdemin approved these changes

2022-12-29 18:11 UTC, merged

2022-12-29 18:16 UTC, peterdemin commented
Thanks!

2022-12-29 18:34 UTC, peterdemin commented
Released 0.0.2: https://github.com/peterdemin/openai-cli/blob/main/CHANGES.rst#002---dec-29-2022